# BossBar color. You can choose between: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE.
# BossBar style. You can choose between: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20.
tps-color: RED
tps-style: SOLID
tps-text: "&aTPS: %tps%"
viewtps-permission: "tviewtps.viewtps"

messages:
  no-permission: "&5TViewTPS &e> &cYou do not have permission to execute this command."
  player-only: "&5TViewTPS &e> &cThis command can only be executed by one player."
  bossbar-shown: "&5TViewTPS &e> &aBossBar displayed with the TPS in real time."
  bossbar-not-configured: "&5TViewTPS &e> &cBossBar is not configured correctly."
  tps-message: "&5TViewTPS &e> &aServer TPS: %tps%"
  version-message: "&aPlugin version: %s"
